cxx_binary(
  name = 'avg_workflow',
  srcs = [
    'avg_workflow.cpp',
  ],
  deps = [
    '//source/algorithm/avg:avg',
    '//workflow/source:train_test_workflow',
  ],
)

cxx_binary(
  name = 'movie_avg_workflow',
  srcs = [
    'movie_avg_workflow.cpp',
  ],
  deps = [
    '//source/algorithm/avg:movie_avg',
    '//workflow/source:train_test_workflow',
  ],
)