cxx_library(
  name = 'svd_model',
  header_namespace = 'algorithm',
  srcs = [
    'svd_model.cpp',
  ],
  exported_headers = [
    'svd_model.h',
  ],
  deps = [
    '//source/algorithm/base:base_model',
  ],
  visibility = [
    'PUBLIC',
  ],
)