cxx_library(
  name = 'base_model',
  header_namespace = 'algorithm',
  srcs = [
    'base_model.cpp'
  ],
  exported_headers = [
    'base_model.h'
  ],
  deps = [
    '//source/util:data_constants',
  ],
  visibility = [
    'PUBLIC',
  ]
)