cxx_library(
  name = 'avg',
  header_namespace = 'algorithm',
  srcs = [
    'avg.cpp',
  ],
  exported_headers = [
    'avg.h',
  ],
  deps = [
    '//source/algorithm/base:base_model',
    '//source/util:data_constants',
  ],
  visibility = [
    'PUBLIC',
  ],
)