cxx_binary(
  name = 'svd_workflow',
  srcs = [
    'svd_workflow.cpp',
  ],
  deps = [
    '//source/model/svd:svd',
    '//source/util:data_constants',
    '//source/util:data_loader',
    '//source/util:timer',
  ],
)